info:
  model_name: Object Detection
dataset:
  name: &dataset_name udacity
  root_dataset: &root_dataset object-dataset/
  dataset_path: !join [*root_dataset, *dataset_name]
  tfrecords_train_path: !join [*root_dataset, udacity_train.tfrecords]
  tfrecords_test_path: !join [*root_dataset, udacity_test.tfrecords]
  test_size: 0.3
  num_classes: 5
hyperparams:
  batch_size: &batch_size 1
  num_classes: 5
  num_epoches: 100
  num_iterations: 5
  learning_rate: 0.001
udacity:
  name: &udacity_dataset_name Udacity
  root_dataset: &udacity_root_dataset object-dataset/
  dataset_path: !join [*udacity_root_dataset, 'udacity']
  tfrecords_train_path: !join [*udacity_root_dataset, udacity_train.tfrecords]
  tfrecords_test_path: !join [*udacity_root_dataset, udacity_test.tfrecords]
  test_size: 0.2
  num_classes: 5
rovit:
  name: &rovit_dataset_name RoVIT
  root_dataset: &rovit_root_dataset /home/zvadaada/rovit-dataset
  dataset_path: /home/zvadaada/rovit-dataset
  tfrecords_train_path: !join [*rovit_root_dataset, RoVIT_train.tfrecords]
  tfrecords_test_path: !join [*rovit_root_dataset, RoVIT_test.tfrecords]
  test_size: 0.2
  num_classes: 7
model:
  model_type: &model_type YOLOv0.3
  trained_path:  trained_models/
  model_description: !join [*model_type, _, b, *batch_size]
  tensorboard_path: !join [tensorboard/, *model_type, _, b, *batch_size]
  restore_trained_model: trained_models/yolo_v1.0/YOLOv0.4_b32-104600 #!join [trained_models/, *model_type, _, b, *batch_size, -4010]
yolo:
  image_height: 416
  image_width: 416
  grid_size: 13
  boxes_per_cell: 3
  num_anchors: 3
  anchores: [[0.05524553571428571, 0.045619419642857144], [0.022042410714285716, 0.029296875], [0.13853236607142858, 0.10407366071428571]]
