info:
  model_name: YOLO Object Detection
dataset:
  name: AllDataset
  root_dataset: &root_dataset /dataset
  dataset_path: /dataset/all_dataset
  tfrecords_train_path: !join [*root_dataset, udacity_train.tfrecords]
  tfrecords_test_path: !join [*root_dataset, udacity_test.tfrecords]
  preserve_aspect_ratio: True
  test_size: 0.2
  num_classes: 9
bdd:
  name: BerkeleyDD
  root_dataset: &bdd_root_dataset /Users/adam.zvada/Documents/Dataset/BDD/ #/home/zvadaada/BDD/
  dataset_path: !join [*bdd_root_dataset, 'bdd100k']
  tfrecords_train_path: !join [*bdd_root_dataset , udacity_train.tfrecords]
  tfrecords_test_path: !join [*bdd_root_dataset , udacity_test.tfrecords]
  test_size: 0.2
  num_classes: 10
udacity:
  name: Udacity
  root_dataset: &udacity_root_dataset dataset/
  dataset_path: !join [*udacity_root_dataset, 'udacity']
  tfrecords_train_path: !join [*udacity_root_dataset, udacity_train.tfrecords]
  tfrecords_test_path: !join [*udacity_root_dataset, udacity_test.tfrecords]
  test_size: 0.2
  num_classes: 5
rovit:
  name: RoVIT
  root_dataset: &rovit_root_dataset dataset/ #/home/zvadaada/
  dataset_path: !join [*rovit_root_dataset, 'rovit-dataset']
  tfrecords_train_path: !join [*rovit_root_dataset, RoVIT_train.tfrecords]
  tfrecords_test_path: !join [*rovit_root_dataset, RoVIT_test.tfrecords]
  test_size: 0.2
  num_classes: 7
fuzee:
  name: FuzeeTraffic
  root_dataset: &fuzee_root_dataset dataset/ #/home/zvadaada/
  dataset_path: !join [*fuzee_root_dataset , 'fuzee-traffic-dataset']
  tfrecords_train_path: !join [*fuzee_root_dataset , RoVIT_train.tfrecords]
  tfrecords_test_path: !join [*fuzee_root_dataset , RoVIT_test.tfrecords]
  test_size: 0.2
  num_classes: 4
hyperparams:
  batch_size: &batch_size 1
  num_classes: 9
  num_epoches: 20
  num_iterations: 5000
  learning_rate: 0.001
model:
  model_type: &model_type YOLOv1.0
  trained_path:  trained_models/
  model_description: !join [*model_type, _, b, *batch_size]
  tensorboard_path: !join [tensorboard/, *model_type, _, b, *batch_size]
  restore_trained_model: trained_models/yolo_v1.0/YOLOv1.1_b16-1210000 #!join [trained_models/, *model_type, _, b, *batch_size, -4010]
yolo:
  image_height: 416
  image_width: 416
  grid_size: 13
  boxes_per_cell: 3
  num_anchors: 3
  anchores: [[0.03984375, 0.06833333334134616], [0.11249999999999999, 0.21666666665865383], [0.40833333334134614, 0.5638888888942307]]
  num_scales: 3
  num_cells_large: 13
  num_cells_medium: 26
  num_cells_small: 52

